version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test01"
s3_bucket = "userstoragebucket"
s3_prefix = "test01"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
